2023-07-21 17:21:35,043 ERROR: Exception on /explore [GET] [in /Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py:1745]
Traceback (most recent call last):
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/zsg/code/python/microblog-sid/app/routes.py", line 141, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/zsg/code/python/microblog-sid/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/zsg/code/python/microblog-sid/app/templates/base.html", line 31, in top-level template code
    {% block content %} {% endblock %}
  File "/Users/zsg/code/python/microblog-sid/app/templates/index.html", line 4, in block 'content'
    <h1>Hi, {{ current_user.username }} {{ user.count }}!</h1>
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user' is undefined
2023-07-21 17:21:48,502 ERROR: Exception on /explore [GET] [in /Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py:1745]
Traceback (most recent call last):
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/zsg/code/python/microblog-sid/app/routes.py", line 141, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/zsg/code/python/microblog-sid/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/zsg/code/python/microblog-sid/app/templates/base.html", line 31, in top-level template code
    {% block content %} {% endblock %}
  File "/Users/zsg/code/python/microblog-sid/app/templates/index.html", line 4, in block 'content'
    <h1>Hi, {{ current_user.username }} {{ user.count }}!</h1>
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user' is undefined
2023-07-21 17:25:11,145 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-21 17:26:53,396 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-21 17:28:54,667 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-21 17:33:29,655 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-21 17:47:13,744 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-31 11:53:28,653 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-31 11:53:42,690 ERROR: Exception on /explore [GET] [in /Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py:1745]
Traceback (most recent call last):
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/zsg/code/python/microblog-sid/app/routes.py", line 144, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).pagenate(
AttributeError: 'Query' object has no attribute 'pagenate'
2023-07-31 12:17:34,684 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-31 12:17:46,495 ERROR: Exception on /index [GET] [in /Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py:1745]
Traceback (most recent call last):
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/zsg/code/python/microblog-sid/app/routes.py", line 25, in index
    posts = current_user.followed_posts.paginate(page=page,
AttributeError: 'function' object has no attribute 'paginate'
2023-07-31 12:19:14,633 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-31 17:38:02,673 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-31 18:00:03,934 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-31 18:01:33,051 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-31 18:03:15,229 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-31 18:05:22,811 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-31 18:18:43,580 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
