2023-07-12 19:05:16,558 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-12 19:05:43,236 ERROR: Exception on /edit_profile [GET] [in /Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py:1745]
Traceback (most recent call last):
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/zsg/code/python/microblog-sid/app/routes.py", line 91, in edit_profile
    form = EditProfileForm()
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2023-07-12 19:05:48,230 ERROR: Exception on /edit_profile [GET] [in /Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py:1745]
Traceback (most recent call last):
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/zsg/code/python/microblog-sid/app/routes.py", line 91, in edit_profile
    form = EditProfileForm()
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2023-07-12 19:07:49,838 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-18 10:49:06,184 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-18 11:26:58,351 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-18 11:27:08,175 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-18 15:27:35,652 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-18 15:27:54,535 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-19 15:36:25,341 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-19 15:38:44,814 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-19 16:27:50,813 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-19 18:37:56,975 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-19 18:44:56,359 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-21 17:01:04,093 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-21 17:01:13,137 ERROR: Exception on / [GET] [in /Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py:1745]
Traceback (most recent call last):
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/zsg/code/python/microblog-sid/app/routes.py", line 25, in index
    posts = current_user.folllowed_posts().all()
AttributeError: 'User' object has no attribute 'folllowed_posts'
2023-07-21 17:03:42,541 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-21 17:07:04,554 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-21 17:08:25,882 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
2023-07-21 17:18:36,603 ERROR: Exception on /explore [GET] [in /Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py:1745]
Traceback (most recent call last):
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/zsg/code/python/microblog-sid/app/routes.py", line 141, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/zsg/code/python/microblog-sid/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/zsg/code/python/microblog-sid/app/templates/base.html", line 31, in top-level template code
    {% block content %} {% endblock %}
  File "/Users/zsg/code/python/microblog-sid/app/templates/index.html", line 4, in block 'content'
    <h1>Hi, {{ current_user.username }} {{ user.count }}!</h1>
  File "/Users/zsg/code/python/microblog-sid/ve/lib/python3.7/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user' is undefined
2023-07-21 17:21:22,860 INFO: Microblog startup [in /Users/zsg/code/python/microblog-sid/app/__init__.py:51]
